version: "3.8"
services:
  postgres:
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_USER=painappuru
      - POSTGRES_PASSWORD=paina_purru_purru
    volumes:
      - postgres:/var/lib/postgresql/painappuru
    ports:
      - "5436:5432"
volumes:
  postgres:
